### ISSUE TITLE
RK3588 in mainline Arm Trusted Firmware (ATF) 

### ISSUE THREAD

**Issue by es-x** [schneid-l/u-boot-orangepi5#5]
RK3588 is merged to mainline Arm Trusted Firmware (ATF)   pls rebuild  u-boot

https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/21840/11..12?tab=comments

**Comment by schneid-l** [comment]
Hello @es-x,
Thank you for this “pleasantly” formulated request.

The next release of TF-A will be in December, I think I'll wait until then.

You're free to fork to make the update, and potentially make a PR here to propose the change.
